name: Container Images

on: push
jobs:
  build:
    # this is to prevent the job to run at forked projects
    if: github.repository == 'kubernetes-sigs/aws-efs-csi-driver'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build container image
      run: |
        docker build -t aws-efs-csi-driver .
    - name: Push to Github registry
      run: |
        USER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
        BRANCH=$(echo $GITHUB_REF | cut -d'/' -f3)
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c -7)
        IMAGE=aws-efs-csi-driver
        if [ "$BRANCH" = "master" ]; then
          TAG=$SHORT_SHA
          LATEST_TAG=latest
        else
          TAG=$BRANCH
        fi
        docker login docker.pkg.github.com -u $USER -p ${{ secrets.REGISTRY_TOKEN }}
        docker tag aws-efs-csi-driver docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE:$TAG
        docker tag aws-efs-csi-driver docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE:$LATEST_TAG
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE:$TAG
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE:$LATEST_TAG
    - name: Push to Dockerhub registry
      run: |
        BRANCH=$(echo $GITHUB_REF | cut -d'/' -f3)
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c -7)
        REPO=amazon/aws-efs-csi-driver
        if [ "$BRANCH" = "master" ]; then
          TAG=$SHORT_SHA
          LATEST_TAG=latest
        else
          TAG=$BRANCH
        fi
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker tag aws-efs-csi-driver $REPO:$TAG
        docker tag aws-efs-csi-driver $REPO:$LATEST_TAG
        docker push $REPO:$TAG
        docker push $REPO:$LATEST_TAG
